name: BlockPalette
main: me.engineersbox.menuinv.Main
version: 1.1 BETA
author: EngineersBox
description: Block Biome Palettes
commands:
    bp:
        description: Opens The Block Palette For Biome Specific Textures
        usage: /bp
    bp help:
        description: Displays All Help Options For BlockPalette
        usage: /bp help
    bp tool:
        description: Gives Block Biome Tool
        usage: /bp tool
    bp setbiome:
        description: Sets Biome Tool Biome
        usage: /bp setbiome <biome>
    bp getbiome:
        description: Changes Tool To Identify The Biome Of A Selected Block
        usage: /bp getbiome <enable/disable>
    bp biomelist:
        description: Gives Block Biome Tool
        usage: /bp biomelist
    bp chunkinfo:
        description: Displays Chunk Data When Using /bp tool
        usage: /bp chunkinfo <enable/disable>
    bp version:
        description: Displays Plugin Version Information
        usage: /bp version
    bp reload:
        description: Reloads The BlockPalette Plugin
        usage: /bp reload