name: BlockPalette
main: me.engineersbox.menuinv.Main
version: 1.1
author: EngineersBox
description: Block Biome Palettes
commands:
    bp:
        description: Opens The Block Palette For Biome Specific Textures
        usage: /bp
    bp help:
        description: Displays All Help Options For BlockPalette
        usage: /bp help
    bp tool:
        description: Gives Block Biome Tool
        usage: /bp tool
    bp tool biome:
        description: Gives Block Biome Tool
        usage: /bp tool biome <biome>
    bp version:
        description: Displays Plugin Version Information
        usage: /bp version