name: BiomePalette
main: me.engineersbox.menuinv.Main
version: 1.0 (alpha)
author: EngineersBox
description: Block Biome Palettes
commands:
    bp:
        description: Gives You The Biome-Specific Block Palette
        usage: /bp
