name: BiomePalette
main: me.engineersbox.menuinv.Main
version: 1.0 (alpha)
author: EngineersBox
description: Block Biome Palettes
commands:
    bp:
        description: Opens The Block Palette For Biome Alt Textures
        usage: /bp
